#!/bin/bash -e

function checkBroken {
    lnk=$(readlink "$1")

    if [ ${lnk:0:1} != "/" ]; then
        lnk="${1%/*}/$lnk"
    fi
    
    if [[ ! -e $lnk ]]; then
        echo "$2$1"
    fi
}

function recursiveVisit {
    pushd "$1" > /dev/null
    for fileName in *; do
        if [[ -h $fileName ]]; then
            checkBroken "$fileName" "$1/"
        else
            if [[ -d $fileName ]]; then
                recursiveVisit "$fileName"
            fi
        fi
    done
    popd > /dev/null
}

for f; do
    if [[ -d $f ]]; then
        recursiveVisit "$f"
    else
        if [[ -h $f ]]; then
            checkBroken "$f"
        fi
    fi
done
