#!/bin/bash -e

function checkBroken {
    echo "checkBroken: $1"
}

function recursiveVisit {
    pushd "$1" > /dev/null
    for fileName in *; do
        if [[ -h $fileName ]]; then
            checkBroken "$fileName"
        else
            if [[ -d $fileName ]]; then
                recursiveVisit "$fileName"
            fi
        fi
    done
    popd > /dev/null
}

for f; do
    if [[ -d $f ]]; then
        recursiveVisit "$f"
    else
        if [[ -h $f ]]; then
            checkBroken "$f"
        fi
    fi
done
