#!/bin/bash

for f; do
    if [[ -f $f ]]; then
       read -e -p "Enter new file name: " -i "$(basename "$f")" newName
       dirName=`dirname "$f"`
       mv "$f" "${dirName}/${newName}"
    fi
done
