#!/bin/bash

for f
do
    if [ -e "$f" -a "$f" != "." -a "$FILE" != ".." ]
    then
       echo `basename "$f"`
       read newName
       dirName=`dirname "$f"`
       mv "$f" "${dirName}/${newName}"
    fi
done
